name: Build Changed Docker Services

on:
  pull_request:
    branches:
      - main

jobs:
  detect-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find changed services
        id: changes
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $1}' | sort -u | uniq)
          BUILD_SERVICES=()
          for service in $CHANGED; do
            if [[ -f "$service/Dockerfile" ]]; then
              BUILD_SERVICES+=("$service")
            fi
          done
          echo "Changed services: ${BUILD_SERVICES[@]}"
          echo "build_services=${BUILD_SERVICES[@]}" >> "$GITHUB_ENV"

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Docker images
        if: ${{ env.build_services != '' }}
        run: |
          echo "Building and pushing images for: ${{ env.build_services }}"
          for service in $(echo "${{ env.build_services }}" | tr ' ' '\n'); do
            IMAGE_NAME="${{ github.repository }}:${service}-test-build"
            echo "Building image: $IMAGE_NAME"
            cd "$service"
            docker build -t "$IMAGE_NAME" .
            docker push "$IMAGE_NAME"
            cd -
          done
