name: CI/CD for Docker

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-changes:
    if: github.event.pull_request.merged == true  # Запуск только при мерже PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: filter
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $1}' | sort -u | uniq | jq -R -s -c 'split("\n")[:-1]')
          else
            CHANGED="[]"
          fi
          echo "changed_services=$CHANGED" >> "$GITHUB_ENV"
          echo "Detected changes: $CHANGED"