name: Build Changed Docker Services

on:
  pull_request:
    branches:
      - main

jobs:
  detect-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Загружаем 2 последних коммита, чтобы git diff работал

      - name: Find changed services
        id: changes
        run: |
          # Определяем изменённые папки, содержащие Dockerfile
          CHANGED=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $1}' | sort -u | uniq)
          BUILD_SERVICES=()
          for service in $CHANGED; do
            if [[ -f "$service/Dockerfile" ]]; then
              BUILD_SERVICES+=("$service")
            fi
          done
          echo "Changed services: ${BUILD_SERVICES[@]}"
          # Записываем переменную как строку, разделённую пробелами
          echo "build_services=${BUILD_SERVICES[@]}" >> "$GITHUB_ENV"

      - name: Check build_services value
        run: echo "build_services=${{ env.build_services }}"

      - name: Build Docker images
        if: ${{ env.build_services != '' }}
        run: |
          # Проверяем передаваемую строку
          echo "Building images for: ${{ env.build_services }}"
          for service in $(echo "${{ env.build_services }}" | tr ' ' '\n'); do
            IMAGE_NAME="${service}:test-build"
            echo "Building image: $IMAGE_NAME"
            
            docker build -t "$IMAGE_NAME" "$service"
          done
