name: Build Changed Docker Services

env:
  REGISTRY: ghcr.io

on:
  pull_request:
    branches:
      - main

jobs:
  detect-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find changed services
        id: changes
        run: |
          # Получаем измененные директории, ищем только те, которые содержат Dockerfile
          CHANGED=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $1}' | sort -u)
          BUILD_SERVICES=()
          for service in $CHANGED; do
            if [[ -f "$service/Dockerfile" ]]; then
              BUILD_SERVICES+=("$service")
            fi
          done
          echo "Changed services: ${BUILD_SERVICES[@]}"
          
          # Сохраняем найденные сервисы в переменную окружения для использования в дальнейшем
          echo "BUILD_SERVICES=${BUILD_SERVICES[@]}" >> "$GITHUB_ENV"

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker images
        if: ${{ env.BUILD_SERVICES != '' }}
        run: |
          # Собираем и пушим образы для каждого измененного сервиса
          echo "Building and pushing images for: ${{ env.BUILD_SERVICES }}"
          for service in $(echo "${{ env.BUILD_SERVICES }}" | tr ' ' '\n'); do
            IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository }}:${service}-test-build"
            echo "Building image: $IMAGE_NAME"
            cd "$service"
            docker build -t "$IMAGE_NAME" .
            docker push "$IMAGE_NAME"
            cd -
          done
