name: Build and Push API Service

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: api
  SERVICE_TAG: test-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "$REPO_NAME"
          IMAGE_NAME="${{ env.REGISTRY }}/${REPO_NAME}:${{ env.SERVICE_NAME }}-${{ env.SERVICE_TAG }}"
          echo "$IMAGE_NAME"
          docker build -t "$IMAGE_NAME" ./${{ env.SERVICE_NAME }}
          docker push "$IMAGE_NAME"
