name: Build and Push API Service

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: api
  SERVICE_TAG: test-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository }}:${{ env.SERVICE_NAME }}-${{ env.SERVICE_TAG }}"
          docker build -t "$IMAGE_NAME" ./$SERVICE_NAME
          docker push "$IMAGE_NAME"
