name: Build and Push API Service

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: api
  SERVICE_TAG: test-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug token
        run: echo "${{ secrets.GHCR_TOKEN }}" 

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${{ env.REGISTRY }}/${REPO_NAME}:${{ env.SERVICE_NAME }}-${{ env.SERVICE_TAG }}"
          docker build -t "$IMAGE_NAME" ./${{ env.SERVICE_NAME }}
          docker push "$IMAGE_NAME"
